services:
  yolo-pose-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yolo-pose-app
    ports:
      - "8501:8501"
    volumes:
      - ./app.py:/app/app.py
      - ~/.cache:/root/.cache
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    #Comment out the following line if you don't want to use GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]